"use client";
import { useEffect,useState } from "react";
import { Sparkles,Heart,Flower2,Footprints,Mail,Camera,Leaf,Star } from "lucide-react";


import { Item,Event,fundraiser,listingPhotos } from "@/lib/fundraiser";
import { ListingGallery } from "@/components/listing-gallery";
import { impactExamples } from "@/lib/impact";
export default function Fundraiser(){
const [items,setItems]=useState<Item[]>([]),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
async function load(){setLoading(true);try{const r=await fetch("/api/catalog");const d:any=await r.json();if(!r.ok)throw Error(d.error);setItems(d.items);setEvents(d.events);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load the collection.");}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const registrations=[{name:"read_fundraiser_collection",description:"Read published items, choices, stock, and suggested donations.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({items,events})},{name:"start_item_request",description:"Open the request form for an available item. This does not send a request or make a donation.",inputSchema:{type:"object",properties:{itemId:{type:"string"}},required:["itemId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:any)=>{const i=items.find(i=>i.id===input?.itemId&&i.kind!=="soon"&&i.variants.some(v=>v.quantity>0));if(!i)throw new Error("Choose an available item.");choose(i);return {opened:true,itemId:i.id};}}];for(const tool of registrations){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()},[items,events]);
function choose(i:Item){window.location.assign("/request/"+encodeURIComponent(i.id));}
return <><a className="skip" href="#collection">Skip to the collection</a><div className="announcement">FROM THE BAY TO LONDON · RUNNING FOR REFUGEES <Heart size={13}/></div><header className="site-header wrap"><a href="/" className="wordmark">little joys<span>big miles <Sparkles size={19}/></span></a><nav><a href="#collection">The little joys</a><a href="#story">The big why</a><a className="button dark small" href={fundraiser} target="_blank" rel="noreferrer">Donate directly <Heart size={15}/></a></nav></header>
<main><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="mini-spark">✦</span> BRI’S LONDON MARATHON FUNDRAISER · 2027</div><h1>Little joys.<br/>Big miles.<br/><em>A whole lot<br className="desktop"/> of heart.</em></h1><p>Runner goodies, leafy dreams, and small things that do a little good. Help me run London in support of <strong>USA for UNHCR.</strong></p><div className="hero-actions"><a href="#collection" className="button blue">Find your little joy <Sparkles size={18}/></a><span>Bay Area love.<br/>Worldwide impact.</span></div></div><div className="hero-visual"><img src="/hero.png" alt="An illustrative still life of a variegated leaf, colorful star clips, and sparkles on a blue background"/><div className="hero-stamp">GOOD THINGS<br/><Heart size={24} fill="currentColor"/> <br/>FOR A GOOD CAUSE</div><div className="image-caption">A little inspiration. Product photos coming soon.</div></div></section>
<div className="ticker" aria-hidden="true"><span>SMALL JOYS</span> ✦ <span>BIG HEARTS</span> ✦ <span>26.2 MILES</span> ✦ <span>ONE GOOD CAUSE</span> ✦ <span>SMALL JOYS</span> ✦ <span>BIG HEARTS</span></div>
<section id="collection" className="collection wrap"><div className="section-top"><div><div className="eyebrow">A LITTLE SOMETHING FOR YOUR GENEROSITY</div><h2>Pick your kind of joy.</h2></div><p>Find something you love. Send me a request.<br/>I’ll confirm what’s available before you donate.</p></div>{loading?<p role="status">Gathering the little joys…</p>:error?<div className="notice" role="alert">{error} <button onClick={load}>Try again</button></div>:null}<div className="item-grid">{items.map((i,index)=><article className={"item-card "+(i.kind==="soon"?"soon-card":"")} key={i.id}><div className={"item-image tone-"+index+(listingPhotos(i).length?" has-gallery":"")}>{listingPhotos(i).length?<ListingGallery item={i} onRequest={i.kind!=="soon"&&i.variants.some(v=>v.quantity>0)?()=>choose(i):undefined}/>:<div className="photo-pending">{i.id==="clips"?<Star size={45}/>:i.kind==="raffle"?<Leaf size={45}/>:i.id==="sparkles"?<Sparkles size={45}/>:i.kind==="soon"?<Heart size={45}/>:<Flower2 size={45}/>}<span>{i.kind==="soon"?"Something good is rising":"Photos coming soon"}</span></div>}<span className="pill">{i.kind==="soon"?"COMING SOON":i.kind==="raffle"?"BAY AREA RAFFLE":i.id==="clips"?"RUN CLUB FAVORITE":"A LITTLE JOY"}</span></div><div className="item-body"><div className="item-title"><h3>{i.name}</h3>{i.price>0&&<span className="price">${i.price}<small>{i.kind==="raffle"?"/ entry":i.id==="clips"?"/ bundle":"/ each"}</small></span>}</div><p>{i.description}</p>{i.id==="clips"&&<div className="bundle-info">Regular: {i.bundle} for ${i.price} · {i.largeBundle} for ${i.largePrice}<br/>Stars: 4 for ${i.price} · 8 for ${i.largePrice}</div>}{i.kind==="raffle"&&i.ends&&<p>Closes {new Date(i.ends).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles",month:"long",day:"numeric"})}</p>}{i.kind!=="soon"&&(i.variants.some(v=>v.quantity>0)?<button className="button outline" onClick={()=>choose(i)}>{i.kind==="raffle"?"Request raffle entries":"Choose & request"}</button>:<div className="availability">Collection being prepared · check back soon</div>)}</div></article>)}</div></section>
<section className="impact-section wrap" aria-labelledby="impact-heading"><div className="section-top"><div><div className="eyebrow">SMALL GIFTS. REAL POSSIBILITIES.</div><h2 id="impact-heading">A little joy can go a long way.</h2></div><p>Together, our gifts help support refugee families.<br/>Here are a few examples from USA for UNHCR.</p></div><div className="impact-grid">{impactExamples.slice(0,3).map(x=><article key={x.amount}><span className="impact-amount">${x.amount}</span><h3>{x.short}</h3><p>A donation of ${x.amount} {x.text}</p></article>)}</div><p className="impact-source">Examples from USA for UNHCR. These illustrate possible support, rather than a guaranteed allocation of your gift.</p></section><section className="how wrap"><div><div className="eyebrow">SIMPLE, PERSONAL, A LITTLE OLD-SCHOOL</div><h2>Good things happen<br/>in three little steps.</h2></div><ol><li><span>01</span><div><h3>Find your joy</h3><p>Choose an item, color, or bundle and send a quick request.</p></div></li><li><span>02</span><div><h3>Confirm your order</h3><p>I’ll confirm availability of the items you want and share donation info.</p></div></li><li><span>03</span><div><h3>Joy transfer</h3><p>Once the requested donation amount has been made, we’ll coordinate a meetup! See below for coordination info.</p></div></li></ol></section>
{events.length>0&&<section className="wrap events"><div className="eyebrow">LET’S MEET UP</div><h2>A little joy, in person.</h2>{events.map(e=><article className="event" key={e.id}><div><span>{new Date(e.date).toLocaleString("en-US",{timeZone:"America/Los_Angeles",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"})} · {e.place}</span><h3>{e.title}</h3><p>{e.description}</p></div>{e.url&&<a href={e.url} target="_blank" rel="noreferrer" className="button outline">Event details</a>}</article>)}</section>}
<section id="story" className="story"><div className="wrap story-inner"><div className="story-art"><Footprints size={52}/><span>26.2<br/><em>with heart.</em></span></div><div><div className="eyebrow">THE BIG WHY</div><h2>More than a finish line.</h2><p>I’m Bri, a runner in San Mateo, heading to the 2027 London Marathon to raise funds for USA for UNHCR, supporting the UN Refugee Agency.</p><p>For me, 26.2 miles is a challenge I choose. Families fleeing conflict, violence, and persecution may travel hundreds or thousands of miles to find safety. Running is my way of standing in solidarity with them.</p><p>Our donations help UNHCR provide protection, shelter, healthcare, education, and other lifesaving assistance. These little joys bring our community into that bigger journey—one mile and one gift at a time.</p><a href={fundraiser} target="_blank" rel="noreferrer" className="button lime">Visit my official fundraiser <Heart size={18}/></a></div></div></section>
<section className="pickup wrap"><div><div className="eyebrow">BAY AREA ROOTS</div><h2>Let’s coordinate a little handoff.</h2></div><div><p><strong>Hella Bae crew?</strong> We can find a run we’ll both be at through Heylo or Instagram.</p><p><strong>Elsewhere in the Bay?</strong> I’m based in San Mateo. We can arrange a meetup, including somewhere halfway.</p><p className="muted">Local meetups preferred. Mailing barrettes or face sparkles may be possible by arrangement. Plants are pickup only.</p><p>If you have questions or concerns, feel free to email me at <a href="mailto:brs0819@gmail.com">brs0819@gmail.com</a>.</p></div></section></main>
<footer className="wrap"><a href="/" className="wordmark">little joys<span>big miles <Sparkles size={17}/></span></a><p>Made with heart, in the Bay Area.<br/>An independent fundraiser by Bri Solorzano.</p><div><a href="https://instagram.com/kirbriruns" target="_blank" rel="noreferrer"><Camera size={17}/> @kirbriruns</a><a href="https://venmo.com/u/Brianna-Solorzano" target="_blank" rel="noreferrer">Venmo · @Brianna-Solorzano</a><a className="admin-link" href="/admin">Bri’s corner</a></div></footer>
</>}