"use client";
import { useCallback,useEffect,useState } from "react";
import { ChevronLeft,ChevronRight,Images } from "lucide-react";
import { Carousel,CarouselContent,CarouselItem,type CarouselApi } from "@/components/ui/carousel";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Item,ListingPhoto,listingPhotos } from "@/lib/fundraiser";
export function PhotoBrowser({photos,label,compact=false,activeVariantId,onVariantChange,startIndex=0,onExpand}:{photos:ListingPhoto[];label:string;compact?:boolean;activeVariantId?:string;onVariantChange?:(id:string)=>void;startIndex?:number;onExpand?:(index:number)=>void}){
const [api,setApi]=useState<CarouselApi>(),[index,setIndex]=useState(startIndex);
const select=useCallback(()=>{if(!api)return;const i=api.selectedScrollSnap();setIndex(i);const v=photos[i]?.variantId;if(v)onVariantChange?.(v)},[api,photos,onVariantChange]);
useEffect(()=>{if(!api)return;api.on("select",select);api.on("reInit",select);return()=>{api.off("select",select);api.off("reInit",select)}},[api,select]);
useEffect(()=>{if(!api||!activeVariantId)return;const i=photos.findIndex(p=>p.variantId===activeVariantId);if(i>=0&&api.selectedScrollSnap()!==i)api.scrollTo(i)},[api,photos,activeVariantId]);
if(!photos.length)return null;
return <div className={"photo-browser "+(compact?"compact-gallery":"full-gallery")}><Carousel setApi={setApi} opts={{loop:photos.length>1,startIndex}} aria-label={label+" photos"} tabIndex={0}><CarouselContent>{photos.map((photo,i)=><CarouselItem key={photo.id} aria-label={"Photo "+(i+1)+" of "+photos.length}><div className="gallery-slide">{onExpand?<button type="button" className="expand-photo" onClick={()=>onExpand(i)} aria-label={"View all "+label+" photos"}><img src={photo.url} alt={photo.alt||label} loading="lazy"/></button>:<img src={photo.url} alt={photo.alt||label} loading="lazy"/>}</div></CarouselItem>)}</CarouselContent>{photos.length>1&&<><button type="button" className="gallery-nav prev" aria-label={"Previous "+label+" photo"} onClick={()=>api?.scrollPrev()}><ChevronLeft size={20}/></button><button type="button" className="gallery-nav next" aria-label={"Next "+label+" photo"} onClick={()=>api?.scrollNext()}><ChevronRight size={20}/></button><span className="photo-count" aria-live="polite">{index+1} / {photos.length}</span></>}</Carousel><div className="gallery-thumbnails" aria-label={label+" photo thumbnails"}>{photos.slice(0,compact?4:photos.length).map((photo,i)=><button key={photo.id} type="button" className={index===i?"current":""} aria-label={"Show photo "+(i+1)+": "+(photo.alt||label)} aria-pressed={index===i} onClick={()=>api?.scrollTo(i)}><img src={photo.url} alt="" loading="lazy"/></button>)}{compact&&photos.length>4&&<button type="button" className="more-photos" onClick={()=>onExpand?.(index)} aria-label={"View all "+photos.length+" "+label+" photos"}>+{photos.length-4}<Images size={16}/></button>}</div>{!compact&&<div className="photo-caption" aria-live="polite">{photos[index]?.alt||label}</div>}</div>}
export function ListingGallery({item,onRequest}:{item:Item;onRequest?:()=>void}){const [open,setOpen]=useState(false),[start,setStart]=useState(0);const photos=listingPhotos(item);if(!photos.length)return null;return <><PhotoBrowser photos={photos} label={item.name} compact onExpand={i=>{setStart(i);setOpen(true)}}/><Dialog open={open} onOpenChange={setOpen}><DialogContent className="gallery-dialog"><DialogTitle>{item.name}</DialogTitle><DialogDescription>Take a closer look at the little joys. Swipe, use the controls, or pick a thumbnail.</DialogDescription><PhotoBrowser key={start} photos={photos} label={item.name} startIndex={start}/>{onRequest&&<button className="button blue" onClick={()=>{setOpen(false);onRequest()}}>Choose & request</button>}</DialogContent></Dialog></>}
