"use client";
import { useState } from "react";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from "@/components/ui/alert-dialog";
const presets=["#f36b87","#ffb768","#f5e873","#a6d67f","#69c8ad","#83c8ec","#7a95ed","#a9b7ff","#cda6e8","#e5a4cf","#ffffff","#222b45"];
const validColor=(value:string)=>/^#[0-9a-f]{6}$/i.test(value);
export function VariantColorPicker({name,value,onChange,disabled=false}:{name:string;value:string;onChange:(color:string)=>void;disabled?:boolean}){
const [open,setOpen]=useState(false),[draft,setDraft]=useState(value);
function toggle(next:boolean){if(next)setDraft(validColor(value)?value:"#a9b7ff");setOpen(next)}
return <><div className="variant-color-field"><span>Swatch</span><button type="button" className="variant-color-trigger" disabled={disabled} aria-label={"Edit color for "+name} onClick={()=>toggle(true)}><span style={{background:validColor(value)?value:"#a9b7ff"}}/><span>{value}</span></button></div><Dialog open={open} onOpenChange={toggle}><DialogContent className="color-dialog"><DialogTitle>Color for {name}</DialogTitle><DialogDescription>Choose a swatch or a custom color, then apply it. Cancel leaves this choice unchanged.</DialogDescription><div className="color-presets">{presets.map(color=><button type="button" key={color} style={{background:color}} aria-label={"Use color "+color} aria-pressed={draft.toLowerCase()===color} onClick={()=>setDraft(color)}/>)}</div><div className="form-row"><label>Custom color<input type="color" value={validColor(draft)?draft:"#a9b7ff"} onChange={e=>setDraft(e.target.value)}/></label><label>Hex color<input value={draft} maxLength={7} onChange={e=>setDraft(e.target.value)} spellCheck={false} autoComplete="off" placeholder="#a9b7ff"/></label></div>{!validColor(draft)&&<p className="fine" role="status">Enter a color like #a9b7ff.</p>}<div className="color-dialog-actions"><button type="button" className="button outline" onClick={()=>toggle(false)}>Cancel color change</button><button type="button" className="button blue" disabled={!validColor(draft)||draft.toLowerCase()===value.toLowerCase()} onClick={()=>{onChange(draft.toLowerCase());toggle(false)}}>Apply color</button></div></DialogContent></Dialog></>}
export function RemoveChoiceButton({name,onRemove,disabled=false}:{name:string;onRemove:()=>void;disabled?:boolean}){return <AlertDialog><AlertDialogTrigger asChild><button type="button" className="text-button remove-choice" disabled={disabled} aria-label={"Remove choice "+name}>Remove choice</button></AlertDialogTrigger><AlertDialogContent className="remove-choice-dialog"><AlertDialogTitle>Remove “{name}”?</AlertDialogTitle><AlertDialogDescription>This removes the choice from this listing and unlinks its photos. Existing requests keep their details. Save changes to update the site.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel className="button outline">Keep choice</AlertDialogCancel><AlertDialogAction className="button dark" onClick={onRemove}>Yes, remove choice</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
